ItemShareSavedVars =
{
    ["Default"] =
    {
        ["@MoonlitTemplar"] =
        {
            ["$AccountWide"] =
            {
                ["sharedItems"] =
                {
                    ["|H0:item:43532:370:50:0:0:0:0:0:0:0:0:0:0:0:0:24:0:0:0:10000:0|h|h||inventory:seren valis"] =
                    {
                        ["itemLink"] = "|H0:item:43532:370:50:0:0:0:0:0:0:0:0:0:0:0:0:24:0:0:0:10000:0|h|h",
                        ["locationKey"] = "inventory:seren valis",
                        ["lastDumpedAt"] = 1776846201,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Seren Valis)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Weapon",
                        ["quality"] = 3,
                        ["traitType"] = 7,
                        ["accountName"] = "@MoonlitTemplar",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776846101,
                        ["itemKey"] = "|H0:item:43532:370:50:0:0:0:0:0:0:0:0:0:0:0:0:24:0:0:0:10000:0|h|h||inventory:seren valis",
                        ["trait"] = "Sharpened",
                        ["weaponType"] = "Sword",
                        ["weaponHandedness"] = "1H",
                        ["apparelWeight"] = "",
                        ["apparelSlot"] = "",
                        ["slotIndex"] = 4,
                        ["itemType"] = 1,
                        ["itemName"] = "Sword of Twilight's Embrace",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:77811:370:50:0:0:0:0:0:0:0:0:0:0:0:0:24:0:0:0:10000:0|h|h||inventory:seren valis"] =
                    {
                        ["itemLink"] = "|H0:item:77811:370:50:0:0:0:0:0:0:0:0:0:0:0:0:24:0:0:0:10000:0|h|h",
                        ["locationKey"] = "inventory:seren valis",
                        ["lastDumpedAt"] = 1776846203,
                        ["count"] = 1,
                        ["sharedFrom"] = "Inventory (Seren Valis)",
                        ["bagId"] = 1,
                        ["itemTypeName"] = "Weapon",
                        ["quality"] = 4,
                        ["traitType"] = 1,
                        ["accountName"] = "@MoonlitTemplar",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776846103,
                        ["itemKey"] = "|H0:item:77811:370:50:0:0:0:0:0:0:0:0:0:0:0:0:24:0:0:0:10000:0|h|h||inventory:seren valis",
                        ["trait"] = "Powered",
                        ["weaponType"] = "Battle Axe",
                        ["weaponHandedness"] = "2H",
                        ["apparelWeight"] = "",
                        ["apparelSlot"] = "",
                        ["slotIndex"] = 7,
                        ["itemType"] = 1,
                        ["itemName"] = "Battle Axe of Hollow Moons",
                        ["qualityName"] = "Epic",
                    },
                    ["|H0:item:224374:363:50:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] =
                    {
                        ["itemLink"] = "|H0:item:224374:363:50:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776846205,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Apparel",
                        ["quality"] = 4,
                        ["traitType"] = 22,
                        ["accountName"] = "@MoonlitTemplar",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776846105,
                        ["itemKey"] = "|H0:item:224374:363:50:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "Arcane",
                        ["weaponType"] = "",
                        ["weaponHandedness"] = "",
                        ["apparelWeight"] = "",
                        ["apparelSlot"] = "Ring",
                        ["slotIndex"] = 22,
                        ["itemType"] = 2,
                        ["itemName"] = "Ring of the Gorethief",
                        ["qualityName"] = "Epic",
                    },
                    ["|H0:item:95306:362:50:0:0:0:0:0:0:0:0:0:0:0:0:35:0:0:0:10000:0|h|h||bank"] =
                    {
                        ["itemLink"] = "|H0:item:95306:362:50:0:0:0:0:0:0:0:0:0:0:0:0:35:0:0:0:10000:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776846208,
                        ["count"] = 1,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Apparel",
                        ["quality"] = 3,
                        ["traitType"] = 18,
                        ["accountName"] = "@MoonlitTemplar",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776846108,
                        ["itemKey"] = "|H0:item:95306:362:50:0:0:0:0:0:0:0:0:0:0:0:0:35:0:0:0:10000:0|h|h||bank",
                        ["trait"] = "Divines",
                        ["weaponType"] = "",
                        ["weaponHandedness"] = "",
                        ["apparelWeight"] = "Heavy",
                        ["apparelSlot"] = "Feet",
                        ["slotIndex"] = 31,
                        ["itemType"] = 2,
                        ["itemName"] = "Sabatons of the Fire",
                        ["qualityName"] = "Superior",
                    },
                    ["|H0:item:117820:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||furnishingvault"] =
                    {
                        ["itemLink"] = "|H0:item:117820:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "furnishingvault",
                        ["lastDumpedAt"] = 1776846212,
                        ["count"] = 1,
                        ["sharedFrom"] = "Furnishing Vault",
                        ["bagId"] = 18,
                        ["itemTypeName"] = "Furnishing",
                        ["quality"] = 4,
                        ["traitType"] = 0,
                        ["accountName"] = "@MoonlitTemplar",
                        ["furnitureDataId"] = 1339,
                        ["firstDumpedAt"] = 1776846112,
                        ["itemKey"] = "|H0:item:117820:5:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||furnishingvault",
                        ["trait"] = "",
                        ["weaponType"] = "",
                        ["weaponHandedness"] = "",
                        ["apparelWeight"] = "",
                        ["apparelSlot"] = "",
                        ["slotIndex"] = 12,
                        ["itemType"] = 61,
                        ["itemName"] = "Redguard Candelabra, Polished",
                        ["qualityName"] = "Epic",
                    },
                    ["|H0:item:203234:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank"] =
                    {
                        ["itemLink"] = "|H0:item:203234:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h",
                        ["locationKey"] = "bank",
                        ["lastDumpedAt"] = 1776846216,
                        ["count"] = 2,
                        ["sharedFrom"] = "Bank",
                        ["bagId"] = 2,
                        ["itemTypeName"] = "Collectible",
                        ["quality"] = 5,
                        ["traitType"] = 0,
                        ["accountName"] = "@MoonlitTemplar",
                        ["furnitureDataId"] = 0,
                        ["firstDumpedAt"] = 1776846116,
                        ["itemKey"] = "|H0:item:203234:124:1:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0|h|h||bank",
                        ["trait"] = "",
                        ["weaponType"] = "",
                        ["weaponHandedness"] = "",
                        ["apparelWeight"] = "",
                        ["apparelSlot"] = "",
                        ["slotIndex"] = 48,
                        ["itemType"] = 34,
                        ["itemName"] = "Style Page: Earthbone Ayleid Epaulets",
                        ["qualityName"] = "Legendary",
                    }
                }
            }
        }
    }
}
